self.GithubLogo = QtWidgets.QLabel(self.centralwidget)
        self.GithubLogo.setGeometry(QtCore.QRect(660, 0, 71, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.GithubLogo.sizePolicy().hasHeightForWidth())
        self.GithubLogo.setSizePolicy(sizePolicy)
        self.GithubLogo.setText("")
        self.GithubLogo.setPixmap(QtGui.QPixmap("githublogo.png"))
        self.GithubLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.GithubLogo.setObjectName("GithubLogo")
        self.GithubButton = QtWidgets.QPushButton(self.centralwidget)
        self.GithubButton.setGeometry(QtCore.QRect(660, 0, 71, 71))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(18)
        self.GithubButton.setFont(font)
        self.GithubButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.GithubButton.setStyleSheet("\n"
"background-color: rgba(255, 255, 255, 0);")
        self.GithubButton.setText("")
        self.GithubButton.setIconSize(QtCore.QSize(16, 16))
        self.GithubButton.setObjectName("GithubButton")
        url="https://github.com/HARSHSINGH0/EYE_MOUSE"
        self.GithubButton.clicked.connect(lambda:self.linktogithub(url))#e